Game = {}

function Game.EndIf()
	Output("}")
end

local function AddCommand(Command)
	assert(#Command >= 3, "A command table must have at least Name, Min Args and Max Args.")
	
	local Name = Command[1]
	local MinArgs = Command[2]
	local MaxArgs = Command[3]
	local Conditional = Command[4]
	
	Game[Name] = function(...)
		local args = {...}
		
		assert(#args >= MinArgs, Name .. " requires at least " .. MinArgs .. " arguments.")
		assert(#args <= MaxArgs, Name .. " has a maximum of " .. MaxArgs .. " arguments.")
		
		Output(Name)
		Output("(")
		
		if #args > 0 then
			Output("\"")
			Output(table.concat(args, "\",\""))
			Output("\"")
		end
		
		Output(")")
		Output(Conditional and "{" or ";")
	end
end

-- { "CommandName", MinArgs, MaxArgs } OR { "CommandName", MinArgs, MaxArgs, Conditional }
local DefaultCommands = {
	{ "ActivateTrigger", 1, 1 },
	{ "ActivateVehicle", 3, 4 },
	{ "AddAmbientCharacter", 2, 3 },
	{ "AddAmbientNPCWaypoint", 2, 2 },
	{ "AddAmbientNpcAnimation", 1, 2 },
	{ "AddAmbientPcAnimation", 1, 2 },
	{ "AddBehaviour", 2, 7 },
	{ "AddBonusMission", 1, 1 },
	{ "AddBonusMissionNPCWaypoint", 2, 2 },
	{ "AddBonusObjective", 1, 2 },
	{ "AddCharacter", 2, 2 },
	{ "AddCollectible", 1, 4 },
	{ "AddCollectibleStateProp", 3, 3 },
	{ "AddCondition", 1, 2 },
	{ "AddDriver", 2, 2 },
	{ "AddFlyingActor", 5, 5 },
	{ "AddFlyingActorByLocator", 3, 4 },
	{ "AddGagBinding", 5, 5 },
	{ "AddGlobalProp", 1, 1 },
	{ "AddMission", 1, 1 },
	{ "AddNPC", 2, 3 },
	{ "AddNPCCharacterBonusMission", 7, 8 },
	{ "AddObjective", 1, 3 },
	{ "AddObjectiveNPCWaypoint", 2, 2 },
	{ "AddPed", 2, 2 },
	{ "AddPurchaseCarNPCWaypoint", 2, 2 },
	{ "AddPurchaseCarReward", 5, 6 },
	{ "AddSafeZone", 2, 2 },
	{ "AddShield", 2, 2 },
	{ "AddSpawnPoint", 8, 8 },
	{ "AddSpawnPointByLocatorScript", 6, 6 },
	{ "AddStage", 0, 7 },
	{ "AddStageCharacter", 3, 5 },
	{ "AddStageMusicChange", 0, 0 },
	{ "AddStageTime", 1, 1 },
	{ "AddStageVehicle", 3, 5 },
	{ "AddStageWaypoint", 1, 1 },
	{ "AddTeleportDest", 3, 5 },
	{ "AddToCountdownSequence", 1, 2 },
	{ "AddTrafficModel", 2, 3 },
	{ "AddVehicleSelectInfo", 3, 3 },
	{ "AllowMissionAbort", 1, 1 },
	{ "AllowRockOut", 0, 0 },
	{ "AllowUserDump", 0, 0 },
	{ "AmbientAnimationRandomize", 2, 2 },
	{ "AttachStatePropCollectible", 2, 2 },
	{ "BindCollectibleTo", 2, 2 },
	{ "BindReward", 5, 7 },
	{ "CharacterIsChild", 1, 1 },
	{ "ClearAmbientAnimations", 1, 1 },
	{ "ClearGagBindings", 0, 0 },
	{ "ClearTrafficForStage", 0, 0 },
	{ "ClearVehicleSelectInfo", 0, 0 },
	{ "CloseCondition", 0, 0 },
	{ "CloseMission", 0, 0 },
	{ "CloseObjective", 0, 0 },
	{ "ClosePedGroup", 0, 0 },
	{ "CloseStage", 0, 0 },
	{ "CloseTrafficGroup", 0, 0 },
	{ "CreateActionEventTrigger", 5, 5 },
	{ "CreateAnimPhysObject", 2, 2 },
	{ "CreateChaseManager", 3, 3 },
	{ "CreatePedGroup", 1, 1 },
	{ "CreateTrafficGroup", 1, 1 },
	{ "DeactivateTrigger", 1, 1 },
	{ "DebugBreak", 0, 0 },
	{ "DisableHitAndRun", 0, 0 },
	{ "EnableHitAndRun", 0, 0 },
	{ "EnableTutorialMode", 1, 1 },
	{ "GagBegin", 1, 1 },
	{ "GagCheckCollCards", 5, 5 },
	{ "GagCheckMovie", 4, 4 },
	{ "GagEnd", 0, 0 },
	{ "GagPlayFMV", 1, 1 },
	{ "GagSetAnimCollision", 1, 1 },
	{ "GagSetCameraShake", 2, 3 },
	{ "GagSetCoins", 1, 2 },
	{ "GagSetCycle", 1, 1 },
	{ "GagSetInterior", 1, 1 },
	{ "GagSetIntro", 1, 1 },
	{ "GagSetLoadDistances", 2, 2 },
	{ "GagSetOutro", 1, 1 },
	{ "GagSetPersist", 1, 1 },
	{ "GagSetPosition", 1, 3 },
	{ "GagSetRandom", 1, 1 },
	{ "GagSetSound", 1, 1 },
	{ "GagSetSoundLoadDistances", 2, 2 },
	{ "GagSetSparkle", 1, 1 },
	{ "GagSetTrigger", 3, 5 },
	{ "GagSetWeight", 1, 1 },
	{ "GoToPsScreenWhenDone", 0, 0 },
	{ "InitLevelPlayerVehicle", 3, 4 },
	{ "KillAllChaseAI", 1, 1 },
	{ "LinkActionToObject", 5, 5 },
	{ "LinkActionToObjectJoint", 5, 5 },
	{ "LoadDisposableCar", 3, 3 },
	{ "LoadP3DFile", 1, 3 },
	{ "LucasTest", 0, 16 },
	{ "MoveStageVehicle", 3, 3 },
	{ "MustActionTrigger", 0, 0 },
	{ "NoTrafficForStage", 0, 0 },
	{ "PlacePlayerAtLocatorName", 1, 1 },
	{ "PlacePlayerCar", 2, 2 },
	{ "PreallocateActors", 2, 2 },
	{ "PutMFPlayerInCar", 0, 0 },
	{ "RESET_TO_HERE", 0, 0 },
	{ "RemoveDriver", 1, 1 },
	{ "RemoveNPC", 1, 1 },
	{ "ResetCharacter", 2, 2 },
	{ "ResetHitAndRun", 0, 0 },
	{ "SelectMission", 1, 1 },
	{ "SetActorRotationSpeed", 2, 2 },
	{ "SetAllowSeatSlide", 1, 1 },
	{ "SetAnimCamMulticontName", 1, 1 },
	{ "SetAnimatedCameraName", 1, 1 },
	{ "SetBonusMissionDialoguePos", 3, 4 },
	{ "SetBonusMissionStart", 0, 0 },
	{ "SetBrakeScale", 1, 1 },
	{ "SetBurnoutRange", 1, 1 },
	{ "SetCMOffsetX", 1, 1 },
	{ "SetCMOffsetY", 1, 1 },
	{ "SetCMOffsetZ", 1, 1 },
	{ "SetCamBestSide", 1, 2 },
	{ "SetCarAttributes", 5, 5 },
	{ "SetCarStartCamera", 1, 1 },
	{ "SetCharacterPosition", 3, 3 },
	{ "SetCharacterScale", 1, 1 },
	{ "SetCharacterToHide", 1, 1 },
	{ "SetCharactersVisible", 1, 1 },
	{ "SetChaseSpawnRate", 2, 2 },
	{ "SetCoinDrawable", 1, 1 },
	{ "SetCoinFee", 1, 1 },
	{ "SetCollectibleEffect", 1, 1 },
	{ "SetCollisionAttributes", 4, 4 },
	{ "SetCompletionDialog", 1, 2 },
	{ "SetCondMinHealth", 1, 1 },
	{ "SetCondTargetVehicle", 1, 1 },
	{ "SetCondTime", 1, 1 },
	{ "SetConditionPosition", 1, 1 },
	{ "SetConversationCam", 2, 3 },
	{ "SetConversationCamDistance", 2, 2 },
	{ "SetConversationCamName", 1, 1 },
	{ "SetConversationCamNpcName", 1, 1 },
	{ "SetConversationCamPcName", 1, 1 },
	{ "SetDamperC", 1, 1 },
	{ "SetDemoLoopTime", 1, 1 },
	{ "SetDestination", 1, 3 },
	{ "SetDialogueInfo", 4, 4 },
	{ "SetDialoguePositions", 2, 4 },
	{ "SetDonutTorque", 1, 1 },
	{ "SetDriver", 1, 1 },
	{ "SetDurationTime", 1, 1 },
	{ "SetDynaLoadData", 1, 2 },
	{ "SetEBrakeEffect", 1, 1 },
	{ "SetFMVInfo", 1, 2 },
	{ "SetFadeOut", 1, 1 },
	{ "SetFollowDistances", 2, 2 },
	{ "SetForcedCar", 0, 0 },
	{ "SetGamblingOdds", 1, 1 },
	{ "SetGameOver", 0, 0 },
	{ "SetGasScale", 1, 1 },
	{ "SetGasScaleSpeedThreshold", 1, 1 },
	{ "SetHUDIcon", 1, 1 },
	{ "SetHasDoors", 1, 1 },
	{ "SetHighRoof", 1, 1 },
	{ "SetHighSpeedGasScale", 1, 1 },
	{ "SetHighSpeedSteeringDrop", 1, 1 },
	{ "SetHitAndRunDecay", 1, 1 },
	{ "SetHitAndRunDecayInterior", 1, 1 },
	{ "SetHitAndRunMeter", 1, 1 },
	{ "SetHitNRun", 0, 0 },
	{ "SetHitPoints", 1, 1 },
	{ "SetInitialWalk", 1, 1 },
	{ "SetIrisTransition", 1, 1 },
	{ "SetIrisWipe", 1, 1 },
	{ "SetLevelOver", 0, 0 },
	{ "SetMass", 1, 1 },
	{ "SetMaxSpeedBurstTime", 1, 1 },
	{ "SetMaxTraffic", 1, 1 },
	{ "SetMaxWheelTurnAngle", 1, 1 },
	{ "SetMissionNameIndex", 1, 1 },
	{ "SetMissionResetPlayerInCar", 1, 1 },
	{ "SetMissionResetPlayerOutCar", 2, 2 },
	{ "SetMissionStartCameraName", 1, 1 },
	{ "SetMissionStartMulticontName", 1, 1 },
	{ "SetMusicState", 2, 2 },
	{ "SetNormalSteering", 1, 1 },
	{ "SetNumChaseCars", 1, 1 },
	{ "SetNumValidFailureHints", 1, 1 },
	{ "SetObjDistance", 1, 1 },
	{ "SetObjTargetBoss", 1, 1 },
	{ "SetObjTargetVehicle", 1, 1 },
	{ "SetParTime", 1, 1 },
	{ "SetParticleTexture", 2, 2 },
	{ "SetPickupTarget", 1, 1 },
	{ "SetPlayerCarName", 2, 2 },
	{ "SetPostLevelFMV", 1, 1 },
	{ "SetPresentationBitmap", 1, 1 },
	{ "SetProjectileStats", 3, 3 },
	{ "SetRaceEnteryFee", 1, 1 },
	{ "SetRaceLaps", 1, 1 },
	{ "SetRespawnRate", 2, 2 },
	{ "SetShadowAdjustments", 8, 8 },
	{ "SetShininess", 1, 1 },
	{ "SetSlipEffectNoEBrake", 1, 1 },
	{ "SetSlipGasScale", 1, 1 },
	{ "SetSlipSteering", 1, 1 },
	{ "SetSlipSteeringNoEBrake", 1, 1 },
	{ "SetSpringK", 1, 1 },
	{ "SetStageAIEvadeCatchupParams", 3, 3 },
	{ "SetStageAIRaceCatchupParams", 5, 5 },
	{ "SetStageAITargetCatchupParams", 3, 3 },
	{ "SetStageCamera", 3, 3 },
	{ "SetStageMessageIndex", 1, 2 },
	{ "SetStageMusicAlwaysOn", 0, 0 },
	{ "SetStageTime", 1, 1 },
	{ "SetStatepropShadow", 2, 2 },
	{ "SetSuspensionLimit", 1, 1 },
	{ "SetSuspensionYOffset", 1, 1 },
	{ "SetSwapDefaultCarLocator", 1, 1 },
	{ "SetSwapForcedCarLocator", 1, 1 },
	{ "SetSwapPlayerLocator", 1, 1 },
	{ "SetTalkToTarget", 1, 4 },
	{ "SetTireGrip", 1, 1 },
	{ "SetTopSpeedKmh", 1, 1 },
	{ "SetTotalGags", 2, 2 },
	{ "SetTotalWasps", 2, 2 },
	{ "SetVehicleAIParams", 3, 3 },
	{ "SetVehicleToLoad", 3, 3 },
	{ "SetWeebleOffset", 1, 1 },
	{ "SetWheelieOffsetY", 1, 1 },
	{ "SetWheelieOffsetZ", 1, 1 },
	{ "SetWheelieRange", 1, 1 },
	{ "ShowHUD", 1, 1 },
	{ "ShowStageComplete", 0, 0 },
	{ "Sleep", 1, 1 },
	{ "StageStartMusicEvent", 1, 1 },
	{ "StartCountdown", 1, 2 },
	{ "StayInBlack", 0, 0 },
	{ "StreetRacePropsLoad", 1, 1 },
	{ "StreetRacePropsUnload", 1, 1 },
	{ "SuppressDriver", 1, 1 },
	{ "SwapInDefaultCar", 0, 0 },
	{ "TaskMessage", 3, 4 },
	{ "TurnGotoDialogOff", 0, 0 },
	{ "UseElapsedTime", 0, 0 },
	{ "UsePedGroup", 1, 1 },
	{ "msPlacePlayerCarAtLocatorName", 1, 1 },
}

local ASFCommands = {
	{ "AddCondTargetModel", 1, 1 },
	{ "AddObjTargetModel", 1, 1 },
	{ "AddParkedCar", 1, 1 },
	{ "AddStageVehicleCharacter", 2, 4 },
	{ "AddVehicleCharacter", 1, 3 },
	{ "AddVehicleCharacterSuppressionCharacter", 2, 2 },
	{ "CHECKPOINT_HERE", 0, 0 },
	{ "DisableTrigger", 1, 1 },
	{ "IfCurrentCheckpoint", 0, 0, true },
	{ "RemoveStageVehicleCharacter", 2, 2 },
	{ "ResetStageHitAndRun", 0, 0 },
	{ "ResetStageVehicleAbductable", 1, 1 },
	{ "SetCarChangeHitAndRunChange", 1, 1 },
	{ "SetCheckpointDynaLoadData", 1, 2 },
	{ "SetCheckpointPedGroup", 1, 1 },
	{ "SetCheckpointResetPlayerInCar", 1, 1 },
	{ "SetCheckpointResetPlayerOutCar", 2, 2 },
	{ "SetCheckpointTrafficGroup", 1, 1 },
	{ "SetCollectibleSoundEffect", 1, 1 },
	{ "SetCondDecay", 1, 2 },
	{ "SetCondDelay", 1, 1 },
	{ "SetCondDisplay", 1, 1 },
	{ "SetCondMessageIndex", 1, 1 },
	{ "SetCondSound", 1, 4 },
	{ "SetCondSpeedRangeKMH", 2, 2 },
	{ "SetCondThreshold", 1, 1 },
	{ "SetCondTotal", 1, 1 },
	{ "SetCondTrigger", 1, 1 },
	{ "SetConditionalParameter", 3, 5 },
	{ "SetHUDMapDrawable", 1, 1 },
	{ "SetHitAndRunDecayHitAndRun", 1, 1 },
	{ "SetHitAndRunFine", 1, 1 },
	{ "SetNoHitAndRunMusicForStage", 0, 0 },
	{ "SetObjCameraName", 1, 1 },
	{ "SetObjCanSkip", 1, 1 },
	{ "SetObjDecay", 1, 2 },
	{ "SetObjExplosion", 2, 3 },
	{ "SetObjMessageIndex", 1, 1 },
	{ "SetObjMulticontName", 1, 1 },
	{ "SetObjNoLetterbox", 1, 1 },
	{ "SetObjSound", 1, 4 },
	{ "SetObjSpeedKMH", 1, 1 },
	{ "SetObjThreshold", 1, 1 },
	{ "SetObjTotal", 1, 1 },
	{ "SetObjTrigger", 1, 1 },
	{ "SetObjUseCameraPosition", 1, 1 },
	{ "SetParkedCarsEnabled", 1, 1 },
	{ "SetPedsEnabled", 1, 1 },
	{ "SetStageAllowMissionCancel", 1, 1 },
	{ "SetStageCarChangeHitAndRunChange", 1, 1 },
	{ "SetStageCharacterModel", 1, 2 },
	{ "SetStageHitAndRun", 1, 1 },
	{ "SetStageHitAndRunDecay", 1, 1 },
	{ "SetStageHitAndRunDecayHitAndRun", 1, 1 },
	{ "SetStageHitAndRunDecayInterior", 1, 1 },
	{ "SetStageHitAndRunFine", 1, 1 },
	{ "SetStageNumChaseCars", 1, 1 },
	{ "SetStagePayout", 1, 1 },
	{ "SetStageVehicleAbductable", 2, 2 },
	{ "SetStageVehicleAllowSeatSlide", 2, 2 },
	{ "SetStageVehicleCharacterAnimation", 3, 4 },
	{ "SetStageVehicleCharacterJumpOut", 2, 3 },
	{ "SetStageVehicleCharacterScale", 3, 3 },
	{ "SetStageVehicleCharacterVisible", 2, 2 },
	{ "SetStageVehicleNoDestroyedJumpOut", 1, 1 },
	{ "SetStageVehicleReset", 2, 2 },
	{ "SetVehicleCharacterAnimation", 2, 3 },
	{ "SetVehicleCharacterJumpOut", 1, 2 },
	{ "SetVehicleCharacterScale", 2, 2 },
	{ "SetVehicleCharacterVisible", 1, 1 },
	{ "SetWheelieOffsetX", 1, 1 },
	{ "UseTrafficGroup", 1, 1 },
}

local StartTime = GetTime()

for i=1,#DefaultCommands do
	AddCommand(DefaultCommands[i])
end

local EndTime = GetTime()

print("Game.lua", "Loaded " .. #DefaultCommands .. " default commands in " .. (EndTime - StartTime) * 1000 .. "ms.")

if IsHackLoaded("AdditionalScriptFunctionality") then
	StartTime = GetTime()
	
	for i=1,#ASFCommands do
		AddCommand(ASFCommands[i])
	end
	
	EndTime = GetTime()
	
	print("Game.lua", "Loaded " .. #ASFCommands .. " ASF commands in " .. (EndTime - StartTime) * 1000 .. "ms.")
end

return Game